name: Validation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Validate catalog data
      run: npx -y -p @larsgw/formica loir-validate-catalog *.csv
    - name: Validate taxon name resources
      run: npx -y -p @larsgw/formica loir-validate-resources resources/txt/*.txt
